### PR TITLE
refactor

### PR DESCRIPTION
**Pull request by e-kwsm**
- build: set cpp_std to c++11
- fix: -Wzero-as-null-pointer-constant
- fix: -Wlogical-not-parentheses
- fix: modernize-redundant-void-arg
- fix: -Wwritable-strings
- refactor: performance-type-promotion-in-math-fn
- refactor: readability-avoid-const-params-in-decls

### CODE REVIEW

**Comment by marvinfriede** [comment]
Thanks for the fixes. Can this be merged?

**Review by awvwgk — APPROVED** [review]
Thanks for sharing. Looks good to me

**Comment by marvinfriede** [comment]
Bump @e-kwsm

**Comment by e-kwsm** [comment]
Yes, this PR is ready.

**Pull request merged**
